steps:
    - id: retrieve-complete-project
        name: "alpine:latest"
        entrypoint: sh
        args:
            - -c
            - |
            ls -la
            gcloud source repos clone ucb-build-release --project=walkio-271711
            ls -la
# # steps:
# #     - id: retrieve-ssh-key
# #         name: 'gcr.io/cloud-builders/gcloud'
# #         # Hope the permission pass
# #         args: ['kms', 'decrypt', '--location', 'global', '--keyring', 'joybrick-walkio-development','--key', 'access-git-key', '--ciphertext-file', 'id_rsa_jb_github.enc', '--plaintext-file', '/root/.ssh/id_rsa_jb_github']
# #         volumes:
# #             - name: 'ssh'
# #             path: /root/.ssh

# #     - id: retrieve-complete-project
# #         # name: gcr.io/cloud-builders/gcloud
# #         name: "alpine:latest"
# #         # entrypoint: bash
# #         entrypoint: sh
# #         args:
# #             - -c
# #             - |
# #                 # # gcloud source repos clone ucb-build-release --project=walkio-271711
# #                 # # # mv /workspace/.ssh/id_rsa /root/.ssh/id_rsa
# #                 apk update && apk add git git-lfs openssh-client rsync
# #                 chmod 600 /root/.ssh/id_rsa
# #                 touch /root/.ssh/known_hosts
# #                 ssh-keyscan github.com >> /root/.ssh/known_hosts
# #                 git lfs install
# #                 git clone git@github.com:Ray-JoyBrick/walkio.git
# #                 # ls -la /workspace/ucb-build-release
# #         volumes:
# #             - name: 'ssh'
# #             path: /root/.ssh

# #     - id: prepare-reference-ready-game-unity
# #         name: gcr.io/cloud-builders/gsutil
# #         entrypoint: bash
# #         args:
# #             - -c
# #             - |
# #                 # ls -la /workspace
# #                 gsutil cp gs://${_GCS_BUCKET}/references.zip /tmp/references.zip
# #                 gsutil cp gs://${_GCS_BUCKET}/_Generated.zip /tmp/_Generated.zip
# #                 # Unzip will create a folder named references in /workspace
# #                 unzip -qq /tmp/references.zip
# #                 unzip -qq /tmp/_Generated.zip
# #                 mkdir game-unity
# #                 # mkdir .ssh
# #                 mv /workspace/daily-talk/daily-talk-unity /workspace/game-unity/
# #                 mv /workspace/daily-talk/game-specific /workspace/game-unity/
# #                 mv /workspace/daily-talk/prepare-ucb-build-release /workspace/game-unity/
# #                 mv /workspace/references /workspace/game-unity/
# #                 mv /workspace/_Generated /workspace/game-unity/daily-talk-unity/Assets/_
# #                 mv /workspace/daily-talk/unity-setup /workspace/game-unity/
# #                 mv /workspace/daily-talk/remove-dsstore.ps1 /workspace/game-unity/
# #                 mv /workspace/daily-talk/setup-game-ref.ps1 /workspace/game-unity/
# #                 # shopt -s extglob
# #                 # rm -r /workspace/!(game-unity)/
# #                 # rm -f .editorconfig
# #                 # rm -r .git
# #                 # rm -f .gitattributes
# #                 # rm -f .gitignore
# #                 # rm -f cloudbuild.yaml
# #                 # # ls -la /workspace
# #                 ls -la /workspace/game-unity

# #     - id: organize-prepared-complete-project
# #         # Get powershell script image from Docker Hub
# #         name: "mcr.microsoft.com/powershell:preview-alpine-3.10"
# #         # It seems that only sh can be used in alpine
# #         entrypoint: sh
# #         args:
# #             - -c
# #             - |
# #             ls -la /workspace

# #             cd /workspace/game-unity
# #             pwsh-preview setup-game-ref.ps1
# #             pwsh-preview remove-dsstore.ps1
# #             pwsh-preview ./prepare-ucb-build-release/CopyNecessaryItem.ps1
# #             cd /workspace/game-unity/unity-setup
# #             pwsh-preview CopyDailyTalkReferences.ps1
# #             cd /workspace
# #             # No tree command in sh
# #             # tree -f -L 4
# #         waitFor:
# #             - prepare-reference-ready-game-unity
        
# #           # - id: retrieve-ssh-key
# #           #   name: 'gcr.io/cloud-builders/gcloud'
# #           #   # Hope the permission pass
# #           #   args: ['kms', 'decrypt', '--location', 'global', '--keyring', 'joybrick-dailytalk-key-ring','--key', 'access-git-key', '--ciphertext-file', 'auto_id_rsa.enc', '--plaintext-file', '/root/.ssh/id_rsa']
# #           #   volumes:
# #           #     - name: 'ssh'
# #           #       path: /root/.ssh
        
# #     - id: grab-ucb-build-release
# #         # name: gcr.io/cloud-builders/gcloud
# #         name: "alpine:latest"
# #         # entrypoint: bash
# #         entrypoint: sh
# #         args:
# #             - -c
# #             - |
# #             apk update && apk add git git-lfs openssh-client rsync
# #             chmod 600 /root/.ssh/id_rsa
# #             touch /root/.ssh/known_hosts
# #             ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts
# #             git lfs install
# #             git clone git@bitbucket.org:jbdailytalk/ucb-release-android.git
# #             # ls -la /workspace/ucb-release-android
# #             # rsync -avhr --exclude '.git' --exclude '_Generated' --delete /workspace/game-unity/daily-talk-unity/ /workspace/ucb-release-android/
# #             rsync -avhr --exclude '.git' --delete /workspace/game-unity/daily-talk-unity/ /workspace/ucb-release-android/
# #             cd /workspace/ucb-release-android
# #             git config --global user.email "auto@giantcroissant.com"
# #             git config --global user.name "AutoGC"
# #             git log
# #             git add .
# #             git commit -m "For building purpose"
# #             git push -u origin master
# #         volumes:
# #             - name: 'ssh'
# #             path: /root/.ssh

# steps:
#     - id: retrieve-ssh-key
#       name: 'gcr.io/cloud-builders/gcloud'
#       # Hope the permission pass
#       args: ['kms', 'decrypt', '--location', 'global', '--keyring', 'joybrick-dailytalk-key-ring','--key', 'access-git-key', '--ciphertext-file', 'auto_id_rsa.enc', '--plaintext-file', '/root/.ssh/id_rsa']
#       volumes:
#         - name: 'ssh'
#           path: /root/.ssh
  
#     - id: retrieve-complete-project
#       # name: gcr.io/cloud-builders/gcloud
#       name: "alpine:latest"
#       # entrypoint: bash
#       entrypoint: sh
#       args:
#         - -c
#         - |
#           # # gcloud source repos clone ucb-build-release --project=daily-talk-263304
#           # # # mv /workspace/.ssh/id_rsa /root/.ssh/id_rsa
#           apk update && apk add git git-lfs openssh-client rsync
#           chmod 600 /root/.ssh/id_rsa
#           touch /root/.ssh/known_hosts
#           ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts
#           git lfs install
#           git clone git@bitbucket.org:jbdailytalk/daily-talk.git
#           # ls -la /workspace/ucb-build-release
#       volumes:
#         - name: 'ssh'
#           path: /root/.ssh
  
#     - id: prepare-reference-ready-game-unity
#       name: gcr.io/cloud-builders/gsutil
#       entrypoint: bash
#       args:
#         - -c
#         - |
#           # ls -la /workspace
#           gsutil cp gs://${_GCS_BUCKET}/references.zip /tmp/references.zip
#           gsutil cp gs://${_GCS_BUCKET}/_Generated.zip /tmp/_Generated.zip
#           # Unzip will create a folder named references in /workspace
#           unzip -qq /tmp/references.zip
#           unzip -qq /tmp/_Generated.zip
#           mkdir game-unity
#           # mkdir .ssh
#           mv /workspace/daily-talk/daily-talk-unity /workspace/game-unity/
#           mv /workspace/daily-talk/game-specific /workspace/game-unity/
#           mv /workspace/daily-talk/prepare-ucb-build-release /workspace/game-unity/
#           mv /workspace/references /workspace/game-unity/
#           mv /workspace/_Generated /workspace/game-unity/daily-talk-unity/Assets/_
#           mv /workspace/daily-talk/unity-setup /workspace/game-unity/
#           mv /workspace/daily-talk/remove-dsstore.ps1 /workspace/game-unity/
#           mv /workspace/daily-talk/setup-game-ref.ps1 /workspace/game-unity/
#           # shopt -s extglob
#           # rm -r /workspace/!(game-unity)/
#           # rm -f .editorconfig
#           # rm -r .git
#           # rm -f .gitattributes
#           # rm -f .gitignore
#           # rm -f cloudbuild.yaml
#           # # ls -la /workspace
#           ls -la /workspace/game-unity
  
#     - id: organize-prepared-complete-project
#       # Get powershell script image from Docker Hub
#       name: "mcr.microsoft.com/powershell:preview-alpine-3.10"
#       # It seems that only sh can be used in alpine
#       entrypoint: sh
#       args:
#         - -c
#         - |
#           ls -la /workspace
  
#           cd /workspace/game-unity
#           pwsh-preview setup-game-ref.ps1
#           pwsh-preview remove-dsstore.ps1
#           pwsh-preview ./prepare-ucb-build-release/CopyNecessaryItem.ps1
#           cd /workspace/game-unity/unity-setup
#           pwsh-preview CopyDailyTalkReferences.ps1
#           cd /workspace
#           # No tree command in sh
#           # tree -f -L 4
#       waitFor:
#         - prepare-reference-ready-game-unity
  
#     # - id: retrieve-ssh-key
#     #   name: 'gcr.io/cloud-builders/gcloud'
#     #   # Hope the permission pass
#     #   args: ['kms', 'decrypt', '--location', 'global', '--keyring', 'joybrick-dailytalk-key-ring','--key', 'access-git-key', '--ciphertext-file', 'auto_id_rsa.enc', '--plaintext-file', '/root/.ssh/id_rsa']
#     #   volumes:
#     #     - name: 'ssh'
#     #       path: /root/.ssh
  
#     - id: grab-ucb-build-release
#       # name: gcr.io/cloud-builders/gcloud
#       name: "alpine:latest"
#       # entrypoint: bash
#       entrypoint: sh
#       args:
#         - -c
#         - |
#           apk update && apk add git git-lfs openssh-client rsync
#           chmod 600 /root/.ssh/id_rsa
#           touch /root/.ssh/known_hosts
#           ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts
#           git lfs install
#           git clone git@bitbucket.org:jbdailytalk/ucb-release-android.git
#           # ls -la /workspace/ucb-release-android
#           # rsync -avhr --exclude '.git' --exclude '_Generated' --delete /workspace/game-unity/daily-talk-unity/ /workspace/ucb-release-android/
#           rsync -avhr --exclude '.git' --delete /workspace/game-unity/daily-talk-unity/ /workspace/ucb-release-android/
#           cd /workspace/ucb-release-android
#           git config --global user.email "auto@giantcroissant.com"
#           git config --global user.name "AutoGC"
#           git log
#           git add .
#           git commit -m "For building purpose"
#           git push -u origin master
#       volumes:
#         - name: 'ssh'
#           path: /root/.ssh
  
#     # # - id: clone-ucb-build-release
#     # #   # name: gcr.io/cloud-builders/git
#     # #   name: gcr.io/cloud-builders/gcloud
#     # #   entrypoint: bash
#     # #   args:
#     # #     - -c
#     # #     - |
#     # #       gcloud source repos clone ucb-build-release --project=daily-talk-263304
#     # #       # # mv /workspace/.ssh/id_rsa /root/.ssh/id_rsa
#     # #       # chmod 600 /root/.ssh/id_rsa
#     # #       # touch /root/.ssh/known_hosts
#     # #       # # ssh-keyscan source.developers.google.com >> /root/.ssh/known_hosts
#     # #       # # git clone ssh://ray@joybrick.cc@source.developers.google.com:2022/p/daily-talk-263304/r/ucb-build-release /workspace/ucb-build-release
#     # #       # ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts
#     # #       # git clone git@bitbucket.org:jbdailytalk/ucb-release-android.git
#     # #       ls -la /workspace
#     # #   # volumes:
#     # #   #   - name: 'ssh'
#     # #   #     path: /root/.ssh
  
#     # - id: merge-with-complete-unity
#     #   # name: gcr.io/cloud-builders/git
#     #   name: gcr.io/cloud-builders/gsutil
#     #   entrypoint: bash
#     #   args:
#     #     - -c
#     #     - |
#     #       # rm -rf /workspace/ucb-release-android/.git
#     #       # mv /workspace/ucb-build-release/.git /workspace/game-unity/daily-talk-unity
  
#     #       # rsync -avhr --exclude '.git' --exclude '_Generated' --delete /workspace/game-unity/daily-talk-unity/ /workspace/ucb-build-release/
#     #       # rsync -r -x '.git' -x '_Generated' -d /workspace/game-unity/daily-talk-unity/ /workspace/ucb-build-release/
#     #       # gsutil rsync -r -x '\.git.*' -x '_Generated' -d /workspace/game-unity/daily-talk-unity /workspace/ucb-build-release
#     #       # gsutil rsync -r -d /workspace/game-unity/daily-talk-unity /workspace/ucb-build-release
#     #       gsutil -q rsync -x ".git" -x "_Generated" -r -d /workspace/game-unity/daily-talk-unity /workspace/ucb-build-release
#     #       # ls -la /workspace
#     #       # ls -la /workspace/game-unity
#     #       # ls -la /workspace/game-unity/daily-talk-unity
#     #       ls -la /workspace/game-unity/daily-talk-unity/Packages
#     #       ls -la /workspace/ucb-build-release
#     #       ls -la /workspace/ucb-build-release/Packages
#     #       ls -la /workspace/ucb-build-release/.git
#     #   # volumes:
#     #   #   - name: 'ssh'
#     #   #     path: /root/.ssh
  
#     # - id: push-back-to-ucb-build-release
#     #   name: gcr.io/cloud-builders/gcloud
#     #   entrypoint: bash
#     #   args:
#     #     - -c
#     #     - |
#     #       cd /workspace/ucb-build-release
#     #       # gcloud init && git config credential.helper gcloud.sh
#     #       # gcloud init
#     #       git remote add google https://source.developers.google.com/p/daily-talk-263304/r/ucb-build-release
#     #       git config --global user.email "auto@giantcroissant.com"
#     #       git config --global user.name "AutoGC"
#     #       git log
#     #       git add .
#     #       git commit -m "For building purpose"
#     #       git push --all google
#     #       # # gcloud source repos clone ucb-build-release --project=daily-talk-263304
#     #       # # # mv /workspace/.ssh/id_rsa /root/.ssh/id_rsa
#     #       # # chmod 600 /root/.ssh/id_rsa
#     #       # # touch /root/.ssh/known_hosts
#     #       # # # ssh-keyscan source.developers.google.com >> /root/.ssh/known_hosts
#     #       # # # git clone ssh://ray@joybrick.cc@source.developers.google.com:2022/p/daily-talk-263304/r/ucb-build-release /workspace/ucb-build-release
#     #       # # ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts
#     #       # # git clone git@bitbucket.org:jbdailytalk/ucb-release-android.git
#     #       ls -la /workspace/ucb-build-release
#     #   volumes:
#     #     - name: 'ssh'
#     #       path: /root/.ssh

